### ISSUE TITLE
Autoupdating CLI

### ISSUE THREAD

**Issue by Zeko369** [andreifilip123/t3-upgrade-web#17]
While I know it technically goes against the "we give you the boilerplate and you update it yourself", it would be fun to do something similar to how `rails upgrade` works where it shows you a diff if you changed the file and it just replaces it with the new if it can handle it (similar to how `blitz recipes` work)

Also I'd be interested in working on this if you're looking for something like this, since that's my main problem with t3-stack (and even blitzjs to some degree but it's much less there since a lot of code is in the lib itself) 😅

**Comment by andreifilip123** [comment]
That's what I actually wanted to start with in the beginning. But after discussions with t3-oss, it seems like there's been several attempts at this and the fact that you can change whatever in your app makes it hard for diffs to work automagically. So that's why we came with this solution where we give you the diff and you handle it yourself.

**Comment by andreifilip123** [comment]
I'd also love that but there are 2 problems I can think of:
1. You need to figure out what features the user _still_ has.
2. If the user moved stuff around, you're out of luck and can't do much

**Comment by Zeko369** [comment]
1. Features can be found quite easily via package.json
2. You can check if the files are in the places they used to be, if not then you can skip it and inform the user 🤷‍♂️ 

It should be fine since most of the time you probably won't be moving things around 🤔

But I do agree that it's a lot harder than some convention-over-configuration framework like rails 😅

**Comment by andreifilip123** [comment]
Mind if I close this ?

**Comment by Zeko369** [comment]
Yeah, this can be revisited later
