### ISSUE TITLE
Figure out ISG in Next

### ISSUE THREAD

**Issue by andreifilip123** [andreifilip123/t3-upgrade-web#7]
Currently, the /diff/[slug] page uses getStaticPaths & getStaticProps to generate all pages based on the diffs existing on disk. While that works, it has raised the build time from 30s to 5m. I'm thinking there's gotta be a way to store the existing cache and only add new diffs somehow

**Comment by Zeko369** [comment]
Would love to help on this one

**Comment by andreifilip123** [comment]
All yours! 👌 If you want, we can have a talk about it and I can share what I tried already. I'll be pretty full tomorrow but maybe on Tuesday we can sync if you want

**Comment by andreifilip123** [comment]
This isn't necessary anymore. I migrated the app to SSR and fetching the diffs from the repo. That should do the job for now.
